version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesdb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/salesdb
      SESSION_SECRET: change_this_secret
      PORT: 4000
      UPLOAD_DIR: /app/server/uploads
    ports:
      - "4000:4000"
    volumes:
      - ./server/uploads:/app/server/uploads
      - ./server:/app/server
volumes:
  db-data:
